# coding: utf-8

# flake8: noqa
"""
    BitMEX API

    ## REST API for the BitMEX Trading Platform  [View Changelog](/app/apiChangelog)  ----  #### Getting Started  Base URI: [https://www.bitmex.com/api/v1](/api/v1)  ##### Fetching Data  All REST endpoints are documented below. You can try out any query right from this interface.  Most table queries accept `count`, `start`, and `reverse` params. Set `reverse=true` to get rows newest-first.  Additional documentation regarding filters, timestamps, and authentication is available in [the main API documentation](/app/restAPI).  *All* table data is available via the [Websocket](/app/wsAPI). We highly recommend using the socket if you want to have the quickest possible data without being subject to ratelimits.  ##### Return Types  By default, all data is returned as JSON. Send `?_format=csv` to get CSV data or `?_format=xml` to get XML data.  ##### Trade Data Queries  *This is only a small subset of what is available, to get you started.*  Fill in the parameters and click the `Try it out!` button to try any of these queries.  * [Pricing Data](#!/Quote/Quote_get)  * [Trade Data](#!/Trade/Trade_get)  * [OrderBook Data](#!/OrderBook/OrderBook_getL2)  * [Settlement Data](#!/Settlement/Settlement_get)  * [Exchange Statistics](#!/Stats/Stats_history)  Every function of the BitMEX.com platform is exposed here and documented. Many more functions are available.  ##### Swagger Specification  [⇩ Download Swagger JSON](swagger.json)  ----  ## All API Endpoints  Click to expand a section.   # noqa: E501

    OpenAPI spec version: 1.2.0
    Contact: support@bitmex.com
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

# import models into model package
from bitmex_swagger.models.api_key import APIKey
from bitmex_swagger.models.access_token import AccessToken
from bitmex_swagger.models.affiliate import Affiliate
from bitmex_swagger.models.announcement import Announcement
from bitmex_swagger.models.chat import Chat
from bitmex_swagger.models.chat_channel import ChatChannel
from bitmex_swagger.models.connected_users import ConnectedUsers
from bitmex_swagger.models.error import Error
from bitmex_swagger.models.error_error import ErrorError
from bitmex_swagger.models.execution import Execution
from bitmex_swagger.models.funding import Funding
from bitmex_swagger.models.index_composite import IndexComposite
from bitmex_swagger.models.inline_response_200 import InlineResponse200
from bitmex_swagger.models.inline_response_200_1 import InlineResponse2001
from bitmex_swagger.models.instrument import Instrument
from bitmex_swagger.models.instrument_interval import InstrumentInterval
from bitmex_swagger.models.insurance import Insurance
from bitmex_swagger.models.leaderboard import Leaderboard
from bitmex_swagger.models.liquidation import Liquidation
from bitmex_swagger.models.margin import Margin
from bitmex_swagger.models.notification import Notification
from bitmex_swagger.models.order import Order
from bitmex_swagger.models.order_book_l2 import OrderBookL2
from bitmex_swagger.models.position import Position
from bitmex_swagger.models.quote import Quote
from bitmex_swagger.models.settlement import Settlement
from bitmex_swagger.models.stats import Stats
from bitmex_swagger.models.stats_history import StatsHistory
from bitmex_swagger.models.stats_usd import StatsUSD
from bitmex_swagger.models.trade import Trade
from bitmex_swagger.models.trade_bin import TradeBin
from bitmex_swagger.models.transaction import Transaction
from bitmex_swagger.models.user import User
from bitmex_swagger.models.user_commission import UserCommission
from bitmex_swagger.models.user_preferences import UserPreferences
from bitmex_swagger.models.wallet import Wallet
from bitmex_swagger.models.x_any import XAny
